[package]
name = "lunatic-vm"
version = "0.1.0"
authors = ["Bernard Kolobara <me@kolobara.com>"]
edition = "2018"
description = "An actor platform built on WebAssembly"
license = "Apache-2.0/MIT"
readme = "Readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-wormhole = "0.2"
wasmtime = {path = "./wasmtime/crates/wasmtime"}
wasmtime-runtime = {path = "./wasmtime/crates/runtime"}
wasmtime-wasi = {path = "./wasmtime/crates/wasi"}
wasi-common = {path = "./wasmtime/crates/wasi-common"}
wiggle = {path = "./wasmtime/crates/wiggle"}
wasmtime-wiggle = {path = "./wasmtime/crates/wiggle/wasmtime"}
wasmtime-wiggle-macro = {path = "./wasmtime/crates/wiggle/wasmtime/macro"}
walrus = "0.18"
smol = "1.2"
easy-parallel = "3"
crossbeam = "0.8"
anyhow = "1.0"
lazy_static = "1.4.0"
dashmap = "3.11"
smallvec = "1.5"

[dev-dependencies]
criterion = "0.3"
rayon = "1.5"
wat = "1.0"
wasmprinter = "0.2"
pretty_assertions = "0.6.1"

[[bench]]
name = "lunatic_benchmark"
harness = false

[[test]]
name = "normalisation_patching_test"
harness = false
